# ==============================
#      EVA MINIMAL CONFIG
# ==============================

print_info() {
    info title
    info underline
    printf "\n"

    info "OS" distro
    info "Kernel" kernel
    info "Uptime" uptime
    info "Packages" packages
    info "Shell" shell
    info "Terminal" term
    info "CPU" cpu
    info "Memory" memory
}

# -------- IMAGE SETTINGS --------

image_backend="kitty"
image_source="${HOME}/.config/neofetch/eva.jpeg"
image_size="350px"
gap=2

# -------- TEXT STYLE --------

bold="on"
underline_enabled="on"
separator=":"

colors=(5 7 4 6 7 7)

# -------- DISABLE USELESS STUFF --------

color_blocks="off"
ascii_distro="off"
